version: '3.7'

services:

  localstack:
    image: localstack/localstack:latest
    container_name: sqs-consumer-localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"